----主题
CREATE TABLE  REPORT_SUBJECT
(
   ID VARCHAR(64) PRIMARY KEY,
   REPORT_TYPE VARCHAR(50) NOT NULL,
   PEROID VARCHAR(8) NOT NULL,
   REPORT_SUBJECT VARCHAR(200),
   CREATE_BY VARCHAR(10),
   CREATE_DATE DATE
)
----内容风格

DROP TABLE REPORT_CONTENT
CREATE TABLE REPORT_CONTENT
(
   ID VARCHAR(64) PRIMARY KEY,
   SUBJECT_ID VARCHAR(64) NOT NULL,
   NODE_TITLE VARCHAR(1000) ,
   NODE_TYPE VARCHAR(20),
   NODE_ORDER INT,
   NODE_PARMS  NVARCHAR(1000),
   NODE_PARMS_ORDER INT,
   NODE_COMMENT NVARCHAR(MAX),
   NODE_CONTENT_STYLE VARCHAR(20),
   NODE_TITLE_STYLE VARCHAR(20),
   NODE_COMMENT_STYLE VARCHAR(20),
   CREATE_BY VARCHAR(10),
   CREATE_DATE DATE
)